### ISSUE TITLE
Migrate database without forcing it's creation

### ISSUE THREAD

**Issue by pztrn** [toras9000/docker-kallithea#1]
Hey, just tried to use your image on already running PostgreSQL server. Created user, database, granted rights, and when I tried to start image using docker-compose it gives me back a very big traceback and whines about database existance.

There is a `--reuse` flag that can be used when trying to create database using kallithea-cli. Can this be used and guarded by environment variable, say, `KALLITHEA_REUSE_DATABASE`?

**Comment by pztrn** [comment]
Actually, it is completely impossible to start this image for first time using already running database server.

**Comment by toras9000** [comment]
Hi

I don't think I fully understand your intentions yet. 
I will write some advice.
But if it doesn't fit your scenario, I don't think you need to use this image. 
Also, I'm a mediocre kallithea user, so I'm not sure if I know more than you. 


You're talking about `--reuse`, so I interpreted it to mean that you're starting to use the new kallithea on your existing PostgreSQL server.  (is it right?)

If so, the situation is different from what you're expecting in the startup script (startup.sh) for this image, and you'll probably need to initialize it manually. 
Maybe with the following procedure. (However, I have never used a setup with reuse option)

- Avoid the startup script and let the shell run.   
`docker-compose run app bash`
- Change to the directory for the configuration file.   
- Perform the initialization operation according to the setup document.   
https://kallithea.readthedocs.io/en/stable/setup.html
   - Creating a config.    
`kallithea-cli config-create kallithea.ini <Options you need>`
   - Rewrite the database connection string in the config file.   
`sqlalchemy.url` in the config file 
   - Initialize the DB schema of kallithea.  
`kallithea-cli db-create --reuse -c kallithea.ini`

The word "Migrate" is included in the title, so I'll clarify it just in case, but the migration described in the README of this image is for upgrading the DB schema with a version upgrade of kallithea.
It is not relevant when initializing the DB. 


But after all, it's probably better to use your script to create your own image than to use this image as is.
